### ISSUE TITLE
Assignment expressions in for loops not implemented

### ISSUE THREAD

**Issue by thommythomaso** [fabianschuiki/moore#190] opened 2020-06-15 15:14 UTC
```for(i=1; i<16; i=i+1)``` in for loop fails :(

**Comment by fabianschuiki** [comment] 2020-06-15 19:18
The compiler complains about the following:
```
compiler bug: lowering of Expr #28 to hir not implemented
  --> /Users/fabian/Code/moore/test/svlog/regr/iss190_assign_expr.sv:5:30-39:
   | 
   |     initial for (i = 1; i < 16; i = i + 1);
   |                                 ^^^^^^^^^  
   = note: Encountered at src/svlog/hir/lowering.rs:1393
```

Duplicate of #172.

**Closed** 2020-06-16 07:14 UTC
Labels: A-hir, C-bug, L-vlog, P-high
